name: authenticate
description: 'Authenticate wit cloud providers'
version: 0.0.1
homepage: https://www.github.com/berkobob/authenticate

environment:
    sdk: '>=3.3.1 <4.0.0'
    flutter: '>=1.17.0'

dependencies:
    flutter:
        sdk: flutter
    googleapis_auth: ^1.5.0
    http: ^1.2.1
    shared_preferences: ^2.2.2
    url_launcher: ^6.2.5

dev_dependencies:
    flutter_lints: ^3.0.0
    flutter_test:
        sdk: flutter

flutter: null
